### ISSUE TITLE
关于《一种位置指纹-最小二乘融合的蓝牙室内定位方法及实现》项目

### ISSUE THREAD

**Issue by CrushLuzsmy** [Charmve/Charmve#1]
作者您好，我通过阅读你发表的文章，对您的项目十分感兴趣。
但是通过文章中的链接跳转来此的时候，发现链接失效了，不知能否再次分享一下您的项目，真是万分感谢！！！

**Comment by Charmve** [comment]
谢谢关注！

文章中的GitHub链接： https://github.com/Charmve/Bluetooth-Location_2D

欢迎一同学习交流。
